services:
  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: pokeuser
      POSTGRES_PASSWORD: 123_Stella
      POSTGRES_DB: pokemon_db
    ports:
      - "5432:5432"
    networks:
      - pg_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge

