version: '3.8'

networks:
  custom_network:
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: pokeuser
      POSTGRES_PASSWORD: 123_Stella
      POSTGRES_DB: pokemon_db
    ports:
      - "5432:5432"
    networks:
      - custom_network
    volumes:
      - psdb-volume:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123_Stella
    ports:
      - "5050:80"
    networks:
      - custom_network

volumes:
  psdb-volume:
